[package]
name = "testing-arkworks"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ff = { git = "https://github.com/arkworks-rs/algebra", features = [ "asm" ], branch = "explicit-derive-feature" }
rand = "0.8.5"

[dev-dependencies]
rand_pcg = "0.3.1"

[patch.crates-io]
ark-ff = { git = "https://github.com/arkworks-rs/algebra", features = [ "asm" ], branch = "explicit-derive-feature" }
